language: python
matrix:
    include:
    - python: "2.7"
      env:
          - AIO_AVAILABLE=false
          - COVERAGERC=".coveragerc-py2"
    - python: "3.4"
      env:
          - AIO_AVAILABLE=false
          - COVERAGERC=".coveragerc-py34"
    - python: "3.5"
      env:
          - AIO_AVAILABLE=false
          - COVERAGERC=".coveragerc"
    - python: "3.6"
      env:
          - AIO_AVAILABLE=true
          - COVERAGERC=".coveragerc"
    - python: "3.7"
      dist: xenial
      sudo: required
      env:
          - AIO_AVAILABLE=true
          - COVERAGERC=".coveragerc"
    - python: "3.8"
      dist: xenial
      sudo: required
      env:
          - AIO_AVAILABLE=true
          - COVERAGERC=".coveragerc"
install:
  - pip install -U pip setuptools wheel
  - pip install -U pytest pytest-cov coveralls
  - sh -c "if [ '$AIO_AVAILABLE' = 'true' ]; then pip install -U pytest-asyncio; fi"
  - pip install -e .
script:
  - py.test --cov-config $COVERAGERC --cov=pydispatch
after_success:
  - coveralls --rcfile="$COVERAGERC"
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  on:
    python: "3.6"
    tags: true
  username: __token__
  password:
    secure: NIm71IwfmsgZkVHb2gNpzX3wGWckPF4ryMX95eoURh0cn3CBEwtdx0n1y2UjIIQMHswzZ13Ksmd1X5q04SMwbr0CBmdfDalH4BZXjhnuHFSeIy6MIZzXDzacAEsbR5FNGjEMgYWxV4bh463sPackQ+qPQFlC5Qv8FA3a+i6Ei6ZtFJDPzaHhRLmnddbX4FeCM8tCri5mLZpK/3fpdiwjRvqtkftNvDxnieSBG/n/dqOGfxQghWLAiqOJV+BlGG7awjMSXcBOjzZsT0SI02bNrSV6vDJI7fKp5hjkb73yBucOd5YVvDZWGIF30thq662Ug9hw37k+EbtHOFjSDgFVXdC3v6PZoiedo42SLPOZ0d/jdGaQIyijkq0Sw+UplBlKBc+7s+sWUFSgjaYOvgyXp4bG6ApDC/yJ5FY7h/GobpsctaZ60lc0lFBSxGasd/pk0KUYCG4A6EXvEh62W4F9gJJXJQ/+g4tn38pX21LCy8lckqgo4Eqwcn4ch6N+7n1U7wVjZBoXXnCT1Q65w1LQmKKiAFPczAwZ5sxs+KXLKPaEnSHZ1OsNZNrcj4kfncxM1zdNMtGZUaw+p3RQs1vHPBNg/0p2tHZ/YHEJFHZd3/4KfyT8sMXXsMwd7jxBievN2XVrK/4PtXWFObhQmmzZGBFn0a09pn6F+map21j3Em4=
